name: My First Workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: welcome message
              run: echo "my forst github action job"
            - name: list files
              run: ls
            - name: read file
              run: cat f1