name: Exploring Variables and Secrets

on: push

env:
       CONTAINER_REGISTRY: docker.io
       DOCKER_USERNAME: kasiviswanath10
       IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/DOCKER_USERNAME/IMAGE_NAME:latest

      - name: Docker login
        env: 
           DOCKER_PASSWORD: Kasi@0923
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        run:  echo docker build -t ${{env.CONTAINER_REGISTRY}}/DOCKER_USERNAME/IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps: 
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest
